/* Amplify Params - DO NOT EDIT
	API_YOURCLEARWAYAPI_BADGETABLE_ARN
	API_YOURCLEARWAYAPI_BADGETABLE_NAME
	API_YOURCLEARWAYAPI_GRAPHQLAPIENDPOINTOUTPUT
	API_YOURCLEARWAYAPI_GRAPHQLAPIIDOUTPUT
	API_YOURCLEARWAYAPI_HOMEBADGETABLE_ARN
	API_YOURCLEARWAYAPI_HOMEBADGETABLE_NAME
	API_YOURCLEARWAYAPI_HOMEOWNERTABLE_ARN
	API_YOURCLEARWAYAPI_HOMEOWNERTABLE_NAME
	API_YOURCLEARWAYAPI_HOMETABLE_ARN
	API_YOURCLEARWAYAPI_HOMETABLE_NAME
	API_YOURCLEARWAYAPI_QUESTIONTABLE_ARN
	API_YOURCLEARWAYAPI_QUESTIONTABLE_NAME
	API_YOURCLEARWAYAPI_RESPONSETABLE_ARN
	API_YOURCLEARWAYAPI_RESPONSETABLE_NAME
	API_YOURCLEARWAYAPI_USERTABLE_ARN
	API_YOURCLEARWAYAPI_USERTABLE_NAME
	AUTH_YOURCLEARWAY677FEEFC_USERPOOLID
	ENV
	REGION
Amplify Params - DO NOT EDIT */

exports.handler = async (event) => {
    // TODO implement
    console.log(JSON.stringify(event, 3));
    const response = {
		rewards: [{
			points: 1,
			tag: 'ENERGY'
		}]
	};
    return response;
};
